### PR TITLE
Add function to return a Gospel Library Online URL (universal link)

### PR DESCRIPTION
**Pull request by samuelbradshaw**
Gospel Library Online URLs are currently formed like this:
https://www.lds.org/languages/eng/content/scriptures/bofm/1-ne/3.7

Sometime next week they're set to switch to this format:
https://www.lds.org/study/scriptures/bofm/1-ne/3.7?lang=eng

Which should be more permanent, so we can start using them. The updated format is live at test.lds.org.

### CODE REVIEW

**Comment by samuelbradshaw** [comment]
Don't merge this yet. Jeff is pushing for a switch to ?id=p7 instead of .7

**Comment by hiltonc** [comment]
Sounds good. Could you add some unit tests also?

**Comment by samuelbradshaw** [comment]
Will do! I've been delaying because I'm waiting for the updated URLs to go live, just to make sure nothing else changes.

**Comment by hiltonc** [comment]
These URLs don't seem to be working on the website :(

Also, is `https://www.lds.org/study/scriptures/ot/isa/40?id=p2-p4,p6-p7,p10#p2` really how the URL should look? I'm surprised, but I guess that standardizes with non-scripture content?

**Comment by samuelbradshaw** [comment]
Yes, the website is pretty buggy still... there's a problem with three-letter book names – it gets mixed up with the language code parser. It's scheduled to be fixed in a patch release on Thursday. Alma works better:
https://www.lds.org/study/scriptures/bofm/alma/40?id=p2-p4,p6-p7,p10#p2
But you'll notice that jumping down the page isn't working quite right either. It works if you change the anchor after the page has loaded, but loading from scratch, it doesn't scroll correctly.

**Comment by samuelbradshaw** [comment]
I guess it depends on your browser – jumping down the page with #p2 works correctly in Chrome, but not Safari, for me.

**Comment by hiltonc** [comment]
This looks great to me, ready to merge?

**Comment by samuelbradshaw** [comment]
Yep, thanks!

**Pull request merged**
